### ISSUE TITLE
Rusty has received his Mean Streets, but Foreign Devils haven't (plus: slobber damage)

### ISSUE THREAD

**Issue by sgbeal** [kuhrusty/MorbadScorepad#17]
Approximately 300-odd Foreign Devils are still awaiting their Mean Streets (and approximately 430-odd are still awaiting their DDHoD 2nd Printing), while Rusty gets to play with his non-stop. According to the most recent KS update, best-case fulfillment of both of those is the week of June 10th.

That's. Not. Fair. We Foreign Devils desperately want our toys.

Anyway... this ticket is really about reporting the ~water~ saliva damage done to my tablet while using this app to browse the digital facsimile of the new content. (*This* is why we sleeve DDoH cards, tokens, and board. *Saliva damage is real*.)

Please fix. Kthxbye.

**Comment by kuhrusty** [comment]
It's pretty nice, too.  (A lot smaller than I expected--in metric, like 3 kilowatts by 2 litres or whatever--but that's fine; I was a little worried it was going to add a bunch of new rules, but the new rules are just a couple half-pages of pretty simple stuff for the new Settlement encounter deck and Plague markers.)  Plus fun new loot etc.  And a few new monster effects (Flash, Abuse, Defile, etc.), although there's no consolidated reference sheet, so now you have to flip between two things when you want to know what Wither does.  And a couple new missions.

**Comment by sgbeal** [comment]
If you're trying to make me feel better, you've failed miserably :|. All this slobber is becoming a real problem.

**Comment by kuhrusty** [comment]
Can I get a status update on this issue?

Note that users affected by this problem should probably not view issue #19.

**Comment by sgbeal** [comment]
Fo-reen shipping will *supposedly* start on or around June 10th. IIRC, KS's project stats said there were approximately 400 non-North American backers, so... probably 1, maybe 2, weeks for fulfillment.

**Comment by sgbeal** [comment]
PS: too late - i read my mails in the order they arrive, and #19 got here first. i say let the users edit the json card list by hand and recompile.

**Comment by sgbeal** [comment]
Okay, mine arrived and is sleeved, so this is no longer a problem. :-D
