### ISSUE TITLE
DangerDeckActivity: add a way to remove cards from the deck

### ISSUE THREAD

**Issue by kuhrusty** [kuhrusty/MorbadScorepad#19]
Played the new Mean Streets "The Deadly Smell of Disease" mission tonight; one of the mission rewards is to remove certain cards from the Danger deck.  The app doesn't support that!

One way to do this might be to add checkboxes for those two cards (displayed only when the Mean Streets expansion is enabled), but in case there are other missions which will do something like this, you probably want a more generic solution which displays a RecyclerView containing a checkbox for each card.

**Comment by kuhrusty** [comment]
AlertDialog.Builder supports a multiple-selection list, so for once the UI part was the easy part.  (Oh, no, I still blew a fair amount of time trying to get the "Remove Cards" button to rotate 90 degrees in a non-stupid way; gave up.)

**Comment by kuhrusty** [comment]
What this bug tells you is, after 200+ hours of table time, I had still never played the **The Scroglin Crown** mission in the base game, as that too has a reward which removes a card from the Danger deck.

> but in case there are other missions which will do something like this, you probably want a more generic solution which displays a RecyclerView containing a checkbox for each card.

I am so smart!!

**Comment by sgbeal** [comment]
Is that the one where the Scroglin King chases you around the map?

https://boardgamegeek.com/thread/2109779/tale-campaign-synergy-and-serendipity

**Comment by kuhrusty** [comment]
No, that's **Throw It In The Pit**, which gave some [hilarious results](https://boardgamegeek.com/article/29160148#29160148) to us too:

> We were given a very specific task to perform, but the mission rules gave us... *considerable leeway* on how strictly we chose to interpret those instructions. "If you don't do this thing, *something terrible* will happen to our town," they told us. We left to do the thing; once out of sight, we agree that the thing will be *hard;* maybe instead we could do something *easy.*
> 
> Upon completion, the river around the town turns to acid & dissolves all the fishing boats. "Well, I think we were done in that town anyway," we tell ourselves.
