### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [kuhrusty/MorbadScorepad#32]
Hi,

Since this app is GNU GPL V3 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by kuhrusty** [comment]
Hey, that's interesting; I hadn't heard of that before.

I was in the middle of some changes for issue #9 last month when I was interrupted by a powerful need to earn some money; I will try to take a look at this in the next few days.  (One thing I'm not clear on is whether we need to add some license file emphasizing that Goblinko's assets--images, text--are definitely *not* free for reuse.)

**Comment by sgbeal** [comment]
> was interrupted by a powerful need to earn some money

FWIW, i cannot hear that in any voice other than Captain Malcomb Reynolds'. (Try it. You'll see.)

**Comment by Poussinou** [comment]
It should be easy to include your app since you're not using any proprietary dependencies.

Let's wait for the different changes you planned, and we'll try to push this app to F-Droid. Regarding the licenses, we'll add add a flag that specifies that some assets (or all assets here) aren't FLOSS, it should be enough.
