### ISSUE TITLE
get permission to distribute Dominican font

### ISSUE THREAD

**Issue by kuhrusty** [kuhrusty/MorbadScorepad#7]
You're using Dominican from haroldsfonts.com; its README says it's free to use, but that the font file itself can't be redistributed.  Get permission to include it in the source tree/APK, or come up with something else.

**Comment by kuhrusty** [comment]
Ohh, it looks like this is no longer a free font.  There are some free Caslon Antique fonts which are similar:

http://www.fontspace.com/alan-carr/caslon-antique
https://www.1001fonts.com/caslon-antique-font.html

**Comment by kuhrusty** [comment]
Those Caslon Antique fonts are not *quite* the same, but they'll work if necessary.  [Here's](http://haroldsfonts.com/font/dominican/) the link to Dominican; I've just asked fontbros.com support what it would cost to license the font.

**Comment by kuhrusty** [comment]
In the meantime, will just use Caslon Antique Bold (which is now checked in).  It's a narrower font, which is not necessarily bad, but it's not quite the *same,* which *is* bad.

**Comment by sgbeal** [comment]
i'll donate 2 cents to that fund: continue to use a "close enough" cost-free font.

**Comment by kuhrusty** [comment]
Yeah, I think I'm going to close this.  I toyed with the idea of *making* a font (I've never done that before & am curious to try), but that's not happening anytime soon.  Caslon Antique Bold it is.
